name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main]
    
jobs:
  markdownlint:
    runs_on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: "**/*.md"